#!/usr/bin/env bash
#
# VPS deployment script for the Unified Trading Bot
# Run this on a fresh Ubuntu/Debian VPS (e.g., Hetzner CX21)
#
# Usage: curl -sSL <raw-github-url>/deploy.sh | bash
#    or: chmod +x deploy.sh && ./deploy.sh
#
set -euo pipefail

REPO="https://github.com/leonlindblad/Trading-bot.git"
BRANCH="claude/unified-trading-bot-cnS2F"
INSTALL_DIR="$HOME/trading-bot"

echo "============================================"
echo "  Unified Trading Bot — VPS Deployment"
echo "============================================"
echo ""

# --- 1. Install Docker if not present ---
if ! command -v docker &> /dev/null; then
    echo "[1/5] Installing Docker..."
    curl -fsSL https://get.docker.com | sh
    sudo usermod -aG docker "$USER"
    echo "  Docker installed. You may need to log out and back in for group changes."
else
    echo "[1/5] Docker already installed."
fi

# --- 2. Install Docker Compose plugin if not present ---
if ! docker compose version &> /dev/null 2>&1; then
    echo "[2/5] Installing Docker Compose plugin..."
    sudo apt-get update -qq && sudo apt-get install -y -qq docker-compose-plugin
else
    echo "[2/5] Docker Compose already installed."
fi

# --- 3. Clone the repo ---
if [ -d "$INSTALL_DIR" ]; then
    echo "[3/5] Updating existing repo..."
    cd "$INSTALL_DIR"
    git fetch origin "$BRANCH"
    git checkout "$BRANCH"
    git pull origin "$BRANCH"
else
    echo "[3/5] Cloning repository..."
    git clone -b "$BRANCH" "$REPO" "$INSTALL_DIR"
    cd "$INSTALL_DIR"
fi

# --- 4. Create .env file ---
if [ ! -f .env ]; then
    echo "[4/5] Creating .env file..."
    DB_PASS=$(openssl rand -base64 24 | tr -d '/+=' | head -c 32)
    cat > .env << ENVEOF
# Auto-generated by deploy.sh — edit as needed
DB_PASSWORD=${DB_PASS}
DATABASE_URL=postgresql+asyncpg://bot:${DB_PASS}@postgres:5432/trading_bot
REDIS_URL=redis://redis:6379/0

# Telegram alerts (set these to receive trade notifications on your phone)
# See: https://core.telegram.org/bots#how-do-i-create-a-bot
TELEGRAM_BOT_TOKEN=
TELEGRAM_CHAT_ID=

PAPER_TRADING=true
API_PORT=8000
ENVEOF
    echo "  .env created with auto-generated DB password."
    echo ""
    echo "  >>> OPTIONAL: Set up Telegram alerts for remote monitoring <<<"
    echo "  1. Message @BotFather on Telegram, send /newbot"
    echo "  2. Copy the token into .env as TELEGRAM_BOT_TOKEN"
    echo "  3. Message your bot, then visit:"
    echo "     https://api.telegram.org/bot<TOKEN>/getUpdates"
    echo "  4. Copy your chat_id into .env as TELEGRAM_CHAT_ID"
    echo ""
else
    echo "[4/5] .env already exists, keeping it."
fi

# --- 5. Start the stack ---
echo "[5/5] Starting trading bot..."
docker compose up -d --build

echo ""
echo "============================================"
echo "  Deployment complete!"
echo "============================================"
echo ""
echo "  Bot is now running in paper trading mode."
echo ""
echo "  Check status:"
echo "    docker compose logs -f bot"
echo ""
echo "  API endpoints:"
echo "    curl http://localhost:8000/api/health"
echo "    curl http://localhost:8000/api/portfolio"
echo "    curl http://localhost:8000/api/trades"
echo "    curl http://localhost:8000/api/positions"
echo "    curl http://localhost:8000/api/strategies"
echo ""
echo "  Stop:"
echo "    cd $INSTALL_DIR && docker compose down"
echo ""
echo "  View logs:"
echo "    docker compose logs -f bot"
echo ""
