"""Base strategy interface."""

from __future__ import annotations

from abc import ABC, abstractmethod
from typing import Any

import pandas as pd

from src.connectors.base import Signal


class BaseStrategy(ABC):
    """Abstract base class for all trading strategies."""

    @property
    @abstractmethod
    def name(self) -> str:
        """Strategy name identifier."""
        ...

    @abstractmethod
    async def evaluate(
        self,
        symbol: str,
        candles: pd.DataFrame,
        current_position: Any | None,
    ) -> Signal | None:
        """Evaluate market data and optionally return a trading signal.

        Args:
            symbol: Trading pair/ticker symbol.
            candles: DataFrame with columns: open, high, low, close, volume.
            current_position: Existing position for this symbol, if any.

        Returns:
            A Signal if a trade should be made, None otherwise.
        """
        ...

    @abstractmethod
    async def on_fill(self, trade: dict) -> None:
        """Called when an order generated by this strategy is filled."""
        ...

    @abstractmethod
    def get_state(self) -> dict:
        """Return serializable state for persistence."""
        ...

    @abstractmethod
    def load_state(self, data: dict) -> None:
        """Restore state from persisted data."""
        ...
