"""Base connector interface and shared domain types."""

from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import datetime, timezone
from decimal import Decimal
from enum import Enum
from typing import Any, Callable
from uuid import uuid4


class Side(str, Enum):
    """Trade side."""

    BUY = "BUY"
    SELL = "SELL"


class OrderType(str, Enum):
    """Order type."""

    MARKET = "MARKET"
    LIMIT = "LIMIT"


class OrderStatus(str, Enum):
    """Order lifecycle status."""

    PENDING = "PENDING"
    FILLED = "FILLED"
    PARTIALLY_FILLED = "PARTIALLY_FILLED"
    CANCELLED = "CANCELLED"
    REJECTED = "REJECTED"


class Market(str, Enum):
    """Supported markets."""

    CRYPTO = "crypto"
    US_STOCKS = "us_stocks"
    UK_STOCKS = "uk_stocks"


@dataclass
class Order:
    """Trade order."""

    symbol: str
    side: Side
    order_type: OrderType
    quantity: Decimal
    market: Market
    strategy: str = ""
    price: Decimal | None = None  # Required for LIMIT orders
    stop_loss: Decimal | None = None
    order_id: str = field(default_factory=lambda: str(uuid4()))
    metadata: dict[str, Any] = field(default_factory=dict)


@dataclass
class OrderResult:
    """Result of an order execution."""

    order_id: str
    exchange_order_id: str
    status: OrderStatus
    filled_quantity: Decimal
    filled_price: Decimal
    fees: Decimal
    symbol: str
    side: Side
    market: Market
    strategy: str = ""
    timestamp: datetime = field(
        default_factory=lambda: datetime.now(timezone.utc)
    )


@dataclass
class OrderBookLevel:
    """Single price level in an order book."""

    price: Decimal
    quantity: Decimal


@dataclass
class OrderBook:
    """Order book snapshot."""

    symbol: str
    bids: list[OrderBookLevel]
    asks: list[OrderBookLevel]
    timestamp: datetime = field(
        default_factory=lambda: datetime.now(timezone.utc)
    )


@dataclass
class PositionInfo:
    """Current position in an asset."""

    symbol: str
    market: Market
    quantity: Decimal
    avg_cost: Decimal
    current_price: Decimal
    unrealised_pnl: Decimal
    strategy: str = ""


@dataclass
class Balance:
    """Account balance."""

    total_equity: Decimal
    available_cash: Decimal
    positions_value: Decimal
    currency: str = "GBP"


@dataclass
class Signal:
    """Trading signal generated by a strategy."""

    symbol: str
    side: Side
    market: Market
    strategy: str
    quantity: Decimal = Decimal("0")
    price: Decimal | None = None
    stop_loss: Decimal | None = None
    reason: str = ""
    metadata: dict[str, Any] = field(default_factory=dict)


class BaseConnector(ABC):
    """Abstract base class for all exchange/broker connectors."""

    def __init__(self, name: str, market: Market):
        self.name = name
        self.market = market
        self._connected = False

    @property
    def is_connected(self) -> bool:
        return self._connected

    @abstractmethod
    async def connect(self) -> bool:
        """Establish connection to the exchange/broker."""
        ...

    @abstractmethod
    async def disconnect(self) -> None:
        """Close connection."""
        ...

    @abstractmethod
    async def get_price(self, symbol: str) -> Decimal:
        """Get current price for a symbol."""
        ...

    @abstractmethod
    async def get_orderbook(self, symbol: str) -> OrderBook:
        """Get current order book for a symbol."""
        ...

    @abstractmethod
    async def place_order(self, order: Order) -> OrderResult:
        """Submit an order for execution."""
        ...

    @abstractmethod
    async def cancel_order(self, order_id: str) -> bool:
        """Cancel a pending order."""
        ...

    @abstractmethod
    async def get_positions(self) -> list[PositionInfo]:
        """Get all current positions."""
        ...

    @abstractmethod
    async def get_balance(self) -> Balance:
        """Get account balance."""
        ...

    @abstractmethod
    async def subscribe_prices(
        self, symbols: list[str], callback: Callable
    ) -> None:
        """Subscribe to real-time price updates."""
        ...
